name: Print hello World

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
      - syncronise

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - run: npm ci
        - run: npm test

        name: Print Hello World
            - name: "Install dependencies"
              run: composer install --ansi --no-interaction --no-progress

            - name: "Say Hello"
              uses: ./actions/print
              with:
                who-to-greet: Maxime
    sayBye:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout du code
              uses: actions/checkout@v2

            - name: "Say Bye"
              run: echo "Goodbye"